name: Build & Publish Docker image

on:
  push:
    branches: [ main ]
  workflow_dispatch:       # permite lanzarlo a mano desde Actions

env:
  IMAGE_NAME: verdictpdf
  REGISTRY: ghcr.io
  OWNER: giomint

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write      # necesario para publicar en GHCR

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.OWNER }}/${{ env.IMAGE_NAME }}:latest
          platforms: linux/amd64,linux/arm64   # multi-arch